apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: db-deployment
spec:
  ports:
  - port: 3306
    name: mysql
  clusterIP: None   # ★ 이게 핵심: Headless Service
  selector:
    app: db-deployment

