apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: default
data:
  apple.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1> I'm Apple </h1>
    </body>
    </html>

  banana.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1> I'm Banana </h1>
    </body>
    </html>

  cherry.html: |
    <!DOCTYPE html>
    <html>
    <body>
      <h1> I'm Cherry </h1>
    </body>
    </html>
