apiVersion: v1
kind: Service
metadata:
  name: apple
  namespace: default
spec:
  selector:
    app: apple
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: banana
  namespace: default
spec:
  selector:
    app: banana
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: cherry
  namespace: default
spec:
  selector:
    app: cherry
  ports:
    - port: 80
      targetPort: 80
